# Generated by Django 4.1.4 on 2023-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Experience',
            field=models.IntegerField(default=None),
        ),
    ]
