# Generated by Django 4.1.4 on 2023-10-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Info', '0002_studentmodel_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Experience',
            field=models.IntegerField(),
        ),
    ]
