# Generated by Django 4.1.4 on 2023-10-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Info', '0003_alter_studentmodel_experience'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModel',
            new_name='Student_Model',
        ),
    ]
