# Generated by Django 4.1.4 on 2023-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Info', '0004_rename_studentmodel_student_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='Experience',
            field=models.IntegerField(default=0),
        ),
    ]
