# Generated by Django 4.1.4 on 2023-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Info', '0005_alter_student_model_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='Experience',
            field=models.IntegerField(blank=True),
        ),
    ]
